apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::348291871474:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-SG7S0Y9O6AVA
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::348291871474:role/UdacityFlaskDeployCBKubectlRole
      username: build
  mapUsers: |
    []
kind: ConfigMap
metadata:
  creationTimestamp: "2020-09-26T21:45:17Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "2494"
  selfLink: /api/v1/namespaces/kube-system/configmaps/aws-auth
  uid: 4c7571e3-4612-4c47-ad7f-48a31b281b95
