apiVersion: v1
kind: ConfigMap
metadata:
  creationTimestamp: "2020-09-26T14:38:39Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1444"
  selfLink: /api/v1/namespaces/kube-system/configmaps/aws-auth
  uid: 7e42b20a-87a8-45e5-aa78-90e7a0b9fc9b
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn:  arn:aws:iam::348291871474:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-1H6M7W4U0TGN4
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::348291871474:role/UdacityFlaskDeployCBKubectlRole
      username: build
  mapUsers: |
    []

